# Generated by Django 5.1.4 on 2025-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('compatible_cars', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock_quantity', models.IntegerField()),
                ('min_order_quantity', models.IntegerField(default=1)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('technical_specification_pdf', models.URLField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
