# Generated by Django 5.1.4 on 2025-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_guide_pdf',
            field=models.FileField(blank=True, null=True, upload_to='product_pdfs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_specification_pdf',
            field=models.FileField(blank=True, null=True, upload_to='product_pdfs/'),
        ),
    ]
