# Generated by Django 5.1.4 on 2025-04-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'role': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
