name: sparehubapps
description: B2B platform for vehicle spare parts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  url_launcher: ^6.1.14  # For opening PDFs in browser/viewer
  flutter_secure_storage: ^9.0.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.1
  fl_chart: ^0.63.0  # Updated to latest version
  logger: ^2.0.2  # For logging API calls and errors

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6  # Required for generating mock classes

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
