name: sparehubapps
description: B2B platform for vehicle spare parts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.5
  fl_chart: ^0.68.0
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  file_picker: ^8.0.7
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300