name: Daily DB Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Dump PostgreSQL database
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
        run: |
          pg_dump --no-owner --no-privileges --format=custom --file=backup.dump
      - name: Upload backup to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: backup.dump
